### ISSUE TITLE
BigQuery error 413 (Request too large) causing task contention in the insight pull queue

### ISSUE THREAD

**Issue by fabito** [stickfigure/objectify-insight#3]
Pullers default batch size (100) might be too large.
The BigQuery insertAll requests are being [rejected due to their size](https://cloud.google.com/bigquery/streaming-data-into-bigquery#quota) - see stacktrace below.
Shall we allow batchSize parameterization (i.e. via Puller constructor ) ? 
Puller should track the number of buckets before sending to BigUploader ?

The following limits apply for streaming data into BigQuery.

* Maximum row size: 20 KB
* Maximum data size of all rows, per insert: 1 MB
* Maximum rows per second: 10,000 rows per second, per table. Exceeding this amount will cause quota_exceeded errors. For additional support up to 100,000 rows per second, per table, please contact a sales representative.
* Maximum rows per request: 500
* Maximum bytes per second: 10 MB per second, per table. Exceeding this amount will cause quota_exceeded errors.

Our guess is that we are exceeding the max rows per request limit.

```java
com.googlecode.objectify.insight.puller.Puller execute: Exception while processing insight data; aborting for now
java.lang.RuntimeException: com.google.api.client.googleapis.json.GoogleJsonResponseException: 413
{
  "code" : 413,
  "errors" : [ {
    "domain" : "global",
    "message" : "Request Too Large",
    "reason" : "requestTooLarge"
  } ],
  "message" : "Request Too Large"
}
	at com.googlecode.objectify.insight.puller.BigUploader.upload(BigUploader.java:80)
	at com.googlecode.objectify.insight.puller.Puller.processOneBatch(Puller.java:84)
	at com.googlecode.objectify.insight.puller.Puller.execute(Puller.java:59)
	at com.googlecode.objectify.insight.servlet.GuicePullerServlet.doGet(GuicePullerServlet.java:32)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.googlecode.objectify.cache.AsyncCacheFilter.doFilter(AsyncCacheFilter.java:59)
	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:49)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:35)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at 
```

**Comment by stickfigure** [comment]
I shrank the default batch size to 20 and made the value configurable. Thanks for the report!
